# -*- coding: utf-8 -*-
"""CSE110_Questions_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrxNyMr49PML7gRADgBK0ZiBHsKhmDFA
"""

#1
var = input("Enter a value: " )
countnum=0
countchar=0

for i in var:
    if ord(i)>=48 and ord(i)<=57:
        countnum=countnum+1

    elif 65<=ord(i.upper()) and ord(i.upper())<=90:
        countchar=countchar+1

#print(countnum)
#print(countchar)
if countnum==0:
    print("word")
elif countchar==0:
    print("Number")

else:
    print("Mixed")



#task1
x = 30
y = 2
Sum = x+y
Production = x*y
Difference = x-y
print(Sum)
print(Production)
print(Difference)

#Task2
x = 30
y = 2
Sum = x+y
Production = x*y
Difference = x-y
print(Sum)
print(Production)
print(Difference)

#Task3
r = int(input("r :"))
import math

x = math.pi
Area = x*r**2
circumtances = 2*x*r
print('Area is:',Area)
print("circumtances is:",circumtances)

#Task4
import math
r = 3.5


x = math.pi
Area = x*r**2
circumtances = 2*x*r
print('Area is:',Area)
print("circumtances is:",circumtances)

#Task5
import math

num = int(input('Enter the num:'))

if(num%2==0):
  print("The num is even")
else:
          print("The num is odd")

#Task10
Marks = int(input("Enter the marks: "))

if Marks>=90:
    print("A")
elif Marks>=80 and Marks <= 89:
    print("B")
elif Marks>=70 and Marks<=79:
    print("C")
elif Marks>=60 and Marks<=69:
    print("D")
elif Marks>=50 and Marks<=59:
    print("E")
else:
    print("F")

#Task6
num = int(input("Enter the integer num: "))

if (num%2==0)or(num%5==0):
  print(num)

else:
    print("Not a multiple")

#Task7
num = int(input("Enter the num: "))

if (num%2==0 and num%5==0):
  print("multiple of both")
if (num%2==0 or num%5==0):
    print(num)

else:
    print("Not a multiple")

#Task8
num = int(input("Enter the integer num: "))

if (num%2==0 and num%5==0):
    print(num)

else:
    print("Not multiple of 2 and 5 both")

#Task9
num = int(input("Enter the integer num: "))

if (num%2!=0 and num%5!=0):
    print(num)

else:
    print("No")

#Task10

num = int(input("Enter the integer num: "))

if (num%2!=0 and num%5
    !=0):
  print(num)
else:
  print("No")

#Task12
import math
working_hour = float(input("Enter the working hour: "))
main_salary = 8000
countworking_hour = 0
if working_hour <= 40:
  countworking_hour = working_hour*200
  print(countworking_hour)
elif working_hour > 40:
  countworking_hour = main_salary+((working_hour-40)*300)
  print(countworking_hour)

#Task13
import math
hour = int(input("Enter the hour: "))

counthour=hour*60*3600

print(counthour)

#Task14

seconds = int(input("Enter Seconds: "))

hours = seconds//3600
extraseconds = seconds%3600
minutes = extraseconds//60
seconds = extraseconds%60

print("Hour:",hours,"Minutes:",minutes,"Seconds:",seconds)

#Task14

import math

S = int(input("Enter the num: "))

if S < 100:
    L = 3000-125*S**2
    print(L)
elif S >= 100:
    L = 12000/(4+(S**2)/14900)
    print(L)

#Task15

hour = int(input("Enter the time: "))

if 4<=hour<=6:
  print("Breakfast")
elif 12<=hour<=13:
  print("Lunch")
elif  16<=hour<=17:
  print("Snacks")
elif  19<=hour<=20:
  print("Dinner")
elif 0<=hour<=23:
  print("Patience is a virtue")

else:
  print("Wrong Time")

